- hosts: win
  gather_facts: no 
  tasks:
  - win_dns_client:
     
adapter_names: '*'

#we need to take input from service now and validate the ip address 	  
      
ipv4_addresses: "{{ip_address}}"

  - win_domain_membership:

#providing the domain names in the portal page it self
     
dns_domain_name: "{{domain_name}}"

#need to take input from service now portal itself	  
    
hostname: "{{physical_server_name}}"

#we need use ansible vault to store the username and password 	  
      
domain_admin_user: "{{ vault_AD_username }}"
domain_admin_password: "{{ vault_AD_password }}"
state: domain
register: dmout

  - win_reboot:
    when: dmout.reboot_required
