- hosts: win
  gather_facts: no 
  tasks:
  - win_dns_client:
     adapter_names: '*'
     ipv4_addresses: 192.168.16.134

  - win_domain_membership:
      dns_domain_name: tech.in
      hostname: test123
      domain_admin_user: tech/administrator 
      domain_admin_password: admin@123
      state: domain
    register: dmout

  - win_reboot:
    when: dmout.reboot_required
